/****** Object:  Table [dbo].[ban_makebill_sizedes_log]    Script Date: 2017-09-02 9:57:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ban_makebill_sizedes_log](
	[mb_number] [varchar](20) NOT NULL,
	[mb_line] [int] NOT NULL,
	[sizeid] [varchar](20) NULL,
	[sizename] [varchar](50) NULL,
	[dufa] [varchar](50) NULL,
	[jumprule_bef] [varchar](15) NULL,
	[jumprule_aft] [varchar](15) NULL,
	[jumpgroup] [varchar](50) NULL,
	[jumpgrouprule] [varchar](100) NULL,
	[item_code] [varchar](20) NULL,
	[item_desc] [varchar](200) NULL,
	[itemtype] [varchar](2) NULL,
	[allowerrrange] [varchar](30) NULL,
	[aallowerrrange] [varchar](100) NULL,
	[remark] [varchar](30) NULL,
	[size1] [varchar](30) NULL,
	[size2] [varchar](30) NULL,
	[size3] [varchar](30) NULL,
	[size4] [varchar](30) NULL,
	[size5] [varchar](30) NULL,
	[size6] [varchar](30) NULL,
	[size7] [varchar](30) NULL,
	[size8] [varchar](30) NULL,
	[size9] [varchar](30) NULL,
	[size10] [varchar](30) NULL,
	[size11] [varchar](30) NULL,
	[size12] [varchar](30) NULL,
	[size13] [varchar](30) NULL,
	[size14] [varchar](30) NULL,
	[size15] [varchar](30) NULL,
	[size16] [varchar](30) NULL,
	[size17] [varchar](30) NULL,
	[size18] [varchar](30) NULL,
	[size19] [varchar](30) NULL,
	[size20] [varchar](30) NULL,
	[asize1] [varchar](30) NULL,
	[asize2] [varchar](30) NULL,
	[asize3] [varchar](30) NULL,
	[asize4] [varchar](30) NULL,
	[asize5] [varchar](30) NULL,
	[asize6] [varchar](30) NULL,
	[asize7] [varchar](30) NULL,
	[asize8] [varchar](30) NULL,
	[asize9] [varchar](30) NULL,
	[asize10] [varchar](30) NULL,
	[asize11] [varchar](30) NULL,
	[asize12] [varchar](30) NULL,
	[asize13] [varchar](30) NULL,
	[asize14] [varchar](30) NULL,
	[asize15] [varchar](30) NULL,
	[asize16] [varchar](30) NULL,
	[asize17] [varchar](30) NULL,
	[asize18] [varchar](30) NULL,
	[asize19] [varchar](30) NULL,
	[asize20] [varchar](30) NULL,
	[picturcode] [varchar](50) NULL,
	[orderid] [int] NULL,
	[washedrealcc] [varchar](20) NULL,
	[jm] [varchar](20) NULL,
	[jmname] [varchar](20) NULL,
	[editusername] [varchar](20) NULL,
	[editdatetime] [datetime] NULL,
	[edittype] [varchar](20) NULL,
	[editver] [int] NULL,
	[szseriesid] [varchar](20) NULL,
	[szseriesconfirm] [bit] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO